{
 "title": "Docker monitoring",
 "description": "Docker monitoring with Prometheus and cAdvisor",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Latence", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latence moyenne",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_sum[1m])\r\n/\r\nrate(django_http_requests_latency_seconds_by_view_method_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latence P99",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(django_http_requests_latency_seconds_by_view_method_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Trafic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Rx",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(container_network_receive_bytes_total{image!=\"\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Tx",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(container_network_transmit_bytes_total{image!=\"\"}[5m])",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Erreurs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Taux de réponse HTTP 2xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(http_requests_total_by_status_total{status=~\"2..\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Taux de réponse HTTP 4xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "targets": [
      {
       "expr": "rate(http_requests_total_by_status_total{status=~\"4..\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Taux de réponse HTTP 5xx",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "targets": [
      {
       "expr": "rate(http_requests_total_by_status_total{status=~\"5..\"}[5m])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "count(container_last_seen{image!=\"\"})"
      }
     ]
    },
    {
     "title": "Total CPU Usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "mbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{image!=\"\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}